In [5]:
list_a = [5,10,100,1000]
list_b = [2,6,30,100]
list_c = []

for x in range(len(list_a)):
    list_c.insert(x,list_a[x] + list_b[x]) 
print(list_c)

[7, 16, 130, 1100]


In [7]:
list_a = [5,10,100,1000]
escalar = 2
list_c = []

for x in range(len(list_a)):
    list_c.insert(x,escalar*list_a[x]) 
print(list_c)

[10, 20, 200, 2000]


# 1 - Suma de Vectores con Numpy

In [8]:
import numpy as np

In [9]:
x = np.array([2,3,4,5])
y = np.array([1,2,3,4])
print(x+y)
print(type(x))

[3 5 7 9]
<class 'numpy.ndarray'>


In [18]:
#Suma de matrices de tamaño 'x'
A = np.array([[1,3,2], [1,0,0], [1,2,2]])
B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])
print(A)
print(B)
A+B

[[1 3 2]
 [1 0 0]
 [1 2 2]]
[[1 0 5]
 [7 5 0]
 [2 1 1]]


array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

# 2 - Multiplicando por un escalar con Numpy

In [10]:
x = np.array([2,3,4,5])
esc = 2
print(x*2)

[ 4  6  8 10]


In [20]:
#Suma de matrices de tamaño 'x'
A = np.array([[1,3,2], [1,0,0], [1,2,2]])
B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])
print(A)
print(B)
A+B

[[1 3 2]
 [1 0 0]
 [1 2 2]]
[[1 0 5]
 [7 5 0]
 [2 1 1]]


array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

# 3 - Producto escalar o interior

In [12]:
x = np.array([2,1,3])
y = np.array([4,6,7])
sum(x*y)

35

In [13]:
# Calculando el producto escalar de los vectores x e y con funcion
np.dot(x,y)

35

In [14]:
x.dot(y)

35

In [15]:
x@y

35

In [16]:
#Calculando la norma del vector X 
np.linalg.norm(x)

3.7416573867739413

In [21]:
#Producto punto de matrices de tamaño 'x'
A = np.array([[1,3,2], [1,0,0], [1,2,2]])
B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])
print(A)
print(B)
A@B

[[1 3 2]
 [1 0 0]
 [1 2 2]]
[[1 0 5]
 [7 5 0]
 [2 1 1]]


array([[26, 17,  7],
       [ 1,  0,  5],
       [19, 12,  7]])

In [23]:
#Ver la dimensión de una matriz
A.shape

#Ver cantidad de elementos de una matri<
A.size

9

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [28]:
#Matriz de 1 a 10 reacomodada en una matriz de 3x3
print(np.arange(1,10).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 4 - La matriz identidad, la matriz inversa, la matriz transpuesta y el determinante

In [31]:
# Calcular el determinante de una matriz
np.linalg.det(A)

-2.0

In [33]:
# Calcular la inversa de una matriz
A = np.array([[1,3,2], [1,0,0], [1,2,2]])
A_inv = np.linalg.inv(A)
A_inv

array([[-2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -0.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00, -5.00000000e-01,  1.50000000e+00]])

In [36]:
#Transponiendo una matriz
#Comando: np.transpose(A) o A.T
A.T

array([[1, 1, 1],
       [3, 0, 2],
       [2, 0, 2]])

# 5 - Sistemas de ecuaciones lineales

In [38]:
#Creando matriz de coeficientes
A = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])
#Creando matriz de resultados Ax = B
B = np.array([6,4,2])
x = np.linalg.solve(A,B)
print(x)

[3.64787565e-16 8.00000000e-01 1.20000000e+00]
